# [build]
#   command = "pnpm run build"
#   publish = "dist"

[build.environment]
NODE_OPTIONS = "--max_old_space_size=4096"

[[redirects]]
from = "/*"
status = 200
to = "/index.html"

[[redirects]]
from = "/sitemap.xml"
status = 200
to = "/sitemap.xml"

[[redirects]]
from = "/sitemap.xsl"
status = 200
to = "/sitemap.xsl"

[[redirects]]
from = "/robots.txt"
status = 200
to = "/robots.txt"

[[redirects]]
from = "/humans.txt"
status = 200
to = "/humans.txt"
